Porting into latest version of transformers & torch
uber-research/PPLM pull request #40
Opened 2021-10-20 10:44 UTC by woosukji

Hi,

Recently I've been working on Conditional Text Generation for [2021 OSAM Hackathon](https://github.com/osamhack2021?q=pplm&type=&language=&sort=) in Korea,
[Our team](https://github.com/osamhack2021/AI_WEB_POOL_YD) tried your paper code, in order to generate some sentences suitable for job application resume,
and during the process we had to do some modification to match our dependencies.

Here I'd like to share the outcomes, with support to latest version of `torch` and `transformers`,
although this version only takes care of PPLM-BOW (i.e. irrelevant dependencies like `torchtext` might cause some errors when trying out PPLM-DISCRIM or so).
BOW scenario was fully tested and seems to be working well.

The main consideration was the discrepancy of input and output schema of `transformers.GPT2LMHeadModel`.
With older version, `past` values would encapsulate query & key tensors (of attention layers) in the same large tensor,
but now they're seperated into tuples, demanding a deeper method for adding two past tensors.

Anyway, just for someone who'd be interested in bringing your awesome works into current projects.

thx!

2021-10-20 10:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber-research/PPLM?pullRequest=40) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber-research/PPLM?pullRequest=40) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber-research/PPLM?pullRequest=40) it.</sub>

2021-11-04 20:18 UTC, w4nderlust approved these changes
they basically added an additinal dimension i believe and you adapted to make it work with that in multiple places, do i read it correctly. All looks food to me

2021-11-04 20:20 UTC, w4nderlust commented
@dathath have you tested it out with our usual prompts by any chance? just to make sure generated texts are comaprable

2022-11-15 15:45 UTC, akshaylive commented
`requirements.txt` should be updated as well, but would love to see some traction on this :)

2022-11-15 22:33 UTC, akshaylive requested changes
Minor change needed to make BOW model work.

2022-11-15 22:33 UTC, akshaylive commented on run_pplm.py
> -                              add_prefix_space=True,
This line is required. Each line in BOW needs a prefix, without which, `bow_indices` is correct. This drastically changes the output of BOW model output due to incorrect gradient computation.

2022-11-15 22:49 UTC, akshaylive commented on run_pplm.py
> -                              add_prefix_space=True,
Additionally, new L241 needs
```
output_hidden_states=True,
return_dict=False
```

2022-12-19 13:44 UTC, closed without merging